services:
  - type: web
    name: coreinventory
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --prefix backend && npm install --include=dev --prefix frontend && npm run build --prefix frontend
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /tmp/coreinventory.db
      - key: ALLOWED_ORIGINS
        sync: false
      - key: FRONTEND_DIST_PATH
        value: ../frontend/dist
